apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-deployment"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: "{{  .Chart.Name }}-selector"
      version: "current"
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}-selector"
        version: "current"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-1
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.servicePort}}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: BROWSER_URL
            value: "stratypus.tk"
          - name: DATABASE_MAX_CONNECTIONS
            value: "10"
          - name: DATABASE_MIN_CONNECTIONS
            value: "0"
          - name: DATABASE_IDLE
            value: "1000"
          - name: DATABASE_AQUIRE
            value: "1000"
          - name: DATABASE_EVICT
            value: "1000"
          - name: DATABASE_SSL
            value: "true"
          - name: DATABASE_CA
            valueFrom:
              secretKeyRef:
                name: msr
                key: DATABASE_CA
          - name: DATABASE_CERT
            valueFrom:
              secretKeyRef:
                name: msr
                key: DATABASE_CERT
          - name: DATABASE_KEY
            valueFrom:
              secretKeyRef:
                name: msr
                key: DATABASE_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: msr
                key: DATABASE_URL
          - name: NOTE_SERVICE_URL
            valueFrom:
              secretKeyRef:
                name: msr
                key: NOTE_SERVICE_URL
          - name: NOTE_SERVICE_USERNAME
            valueFrom:
              secretKeyRef:
                name: msr
                key: NOTE_SERVICE_USERNAME
          - name: NOTE_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: msr
                key: NOTE_SERVICE_PASSWORD
          - name: PORT
            value : "{{ .Values.service.servicePort }}"
        {{- if .Values.image.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.image.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.image.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.image.readinessProbe | indent 10 }}
        {{- end }}